services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQL\Catalogue\Dao\ManufacturerInterface:
    class: OxidEsales\GraphQL\Catalogue\Dao\Manufacturer
    public: true

  OxidEsales\GraphQL\Catalogue\Dao\VendorInterface:
      class: OxidEsales\GraphQL\Catalogue\Dao\Vendor
      public: true

  OxidEsales\GraphQL\Catalogue\Controller\:
    resource: 'src/Controller/*'
    public: true

  OxidEsales\GraphQL\Catalogue\DataType\:
    resource: 'src/DataType/*Factory.php'
    public: true

  OxidEsales\GraphQL\Catalogue\DataObject\:
      resource: 'src/DataObject/*Factory.php'
      public: true

  OxidEsales\GraphQL\Catalogue\Framework\NamespaceMapper:
    class: OxidEsales\GraphQL\Catalogue\Framework\NamespaceMapper
    tags: ['graphql_namespace_mapper']

  OxidEsales\GraphQL\Catalogue\Service\PermissionProvider:
    class: OxidEsales\GraphQL\Catalogue\Service\PermissionProvider
    tags: ['graphql_permission_provider']
